# - name: Wait for Jenkins to start up
#   ansible.builtin.uri:
#     url: http://localhost:8080
#     status_code: 200
#     timeout: 5
#   register: jenkins_service_status
#   # Keep trying for 5 mins in 5 sec intervals
#   retries: 10
#   delay: 5
#   until: >
#       'status' in jenkins_service_status and
#       jenkins_service_status['status'] == 200

- name: Install Jenkins plugins
  community.general.jenkins_plugin:
    name: "{{ item }}"
    url_username: admin
    url_password: admin
    state: present
    timeout: 30
  with_items: "{{ jenkins_plugins }}"
  register: plugin_result
  until: plugin_result is success
  retries: 3
  delay: 2

- name: Copy Golang plugin config file
  ansible.builtin.copy:
    src: /vagrant/files/org.jenkinsci.plugins.golang.GolangBuildWrapper.xml
    dest: /var/lib/jenkins/org.jenkinsci.plugins.golang.GolangBuildWrapper.xml
    owner: jenkins
    group: jenkins
    mode: 0644

- name: Restart Jenkins
  systemd:
    name: jenkins
    state: restarted