---

- name: Install Jenkins plugins
  community.general.jenkins_plugin:
    name: "{{ item }}"
    url_username: admin
    url_password: admin
    state: present
    timeout: 30
  with_items: "{{ jenkins_plugins }}"
  register: plugin_result
  until: plugin_result is success
  retries: 3
  delay: 2

- name: Copy SSH plugin config file
  ansible.builtin.copy:
    src: /vagrant/jenkins/files/org.jvnet.hudson.plugins.SSHBuildWrapper.xml
    dest: /var/lib/jenkins/org.jvnet.hudson.plugins.SSHBuildWrapper.xml
    owner: jenkins
    group: jenkins
    mode: 0644

- name: Copy Golang plugin config file
  ansible.builtin.copy:
    src: /vagrant/jenkins/files/org.jenkinsci.plugins.golang.GolangBuildWrapper.xml
    dest: /var/lib/jenkins/org.jenkinsci.plugins.golang.GolangBuildWrapper.xml
    owner: jenkins
    group: jenkins
    mode: 0644

- name: Restart Jenkins
  systemd:
    name: jenkins
    state: restarted