name: GitHub Actions Demo

on: push
jobs:
  itacad_hw-11:
    runs-on: self-hosted
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Show workspace 
        run: ls -la
