name: IT academy Homework 11

on: 
  push:
  workflow_dispatch:
jobs:
  itacad_hw-11:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACTION_TOKEN }}
      - name: Build WCG Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/wcg:${{ github.sha }} -t ghcr.io/${{ github.repository_owner }}/wcg:latest -f ./09-docker/Dockerfile.multi .
      - name: Publish WCG Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/wcg:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/wcg:latest
