name: IT academy Homework 11

on: push
jobs:
  itacad_hw-11:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ ACTION_TOKEN }}
      - name: Build the WCG Docker image
        run: |
             docker build . --tag ghcr.io/${{ github.actor }}/wcg:latest -f Dockerfile.multi
             docker run ghcr.io/${{ github.actor }}/wcg:latest
             docker push ghcr.io/${{ github.actor }}/wcg:latest
